---
# ==================================================
# PLAY 1: INIT MANAGER
# ==================================================
- name: Initialize Docker Swarm Manager
  hosts: manager
  become: true

  tasks:

    - name: Check swarm state
      command: docker info --format '{{ "{{.Swarm.LocalNodeState}}" }}'
      register: swarm_state
      changed_when: false

    - name: Initialize swarm (only if not active)
      command: docker swarm init --advertise-addr {{ inventory_hostname }}
      when: swarm_state.stdout != "active"

    - name: Get worker join token (from Manager)
      command: docker swarm join-token -q worker
      register: worker_token
      changed_when: false

    - name: Set clean token
      set_fact:
        swarm_worker_token: "{{ worker_token.stdout }}"


# ==================================================
# PLAY 2: JOIN WORKERS
# ==================================================
- name: Join worker nodes to swarm
  hosts: workers
  become: true

  vars:
    manager_ip: "{{ groups['manager'][0] }}"
    worker_token: "{{ hostvars[groups['manager'][0]].swarm_worker_token }}"

  tasks:

    - name: Check swarm state
      command: docker info --format '{{ "{{.Swarm.LocalNodeState}}" }}'
      register: swarm_state
      changed_when: false

    - name: Leave old swarm if exists
      command: docker swarm leave --force
      when: swarm_state.stdout == "active"

    - name: Join swarm
      command: docker swarm join --token {{ worker_token }} {{ manager_ip }}:2377
      when: swarm_state.stdout != "active"


# ==================================================
# PLAY 3: GEO LABELING (MANAGER ONLY)
# ==================================================
- name: Apply Geo labels
  hosts: manager
  become: true

  tasks:

    - name: Get node names
      command: docker node ls --format '{{ "{{.Hostname}}" }}'
      register: nodes
      changed_when: false

    - name: Get node IPs
      command: docker node inspect {{ item }} --format '{{ "{{.Status.Addr}}" }}'
      loop: "{{ nodes.stdout_lines }}"
      register: node_ips
      changed_when: false

    - name: Build node map
      set_fact:
        node_map: "{{ dict(nodes.stdout_lines | zip(node_ips.results | map(attribute='stdout'))) }}"

    - name: Get Geo data
      uri:
        url: "http://ip-api.com/json/{{ item.value }}"
        return_content: yes
      loop: "{{ node_map | dict2items }}"
      register: geo_results

    - name: Build geo map
      set_fact:
        geo_map: >-
          {{
            dict(
              geo_results.results | map(attribute='item.key')
              | zip(
                geo_results.results
                | map(attribute='json.countryCode')
                | map('default','unknown')
                | map('lower')
              )
            )
          }}

    - name: Apply country labels
      command: docker node update --label-add country={{ geo_map[item] }} {{ item }}
      loop: "{{ nodes.stdout_lines }}"
